name: Run nfl scraper

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "00 18 * * 4" # every Thursday at noon ct

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        # with:
        #   chromedriver-version: "88.0.4324.96" # Optional: Specify the ChromeDriver version here

      - name: Run ChromeDriver and Xvfb
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # Optional: Starts Xvfb with specified display size

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PRODUCTION: ${{ secrets.PRODUCTION }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: python nflScraper.py
